name: Run pytest on push and manual trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FLASK_ENV: ${{ env.FLASK_ENV }}
  SECRET_KEY: ${{ env.SECRET_KEY }}
  BASE_URL: ${{ env.BASE_URL }}
  ENV: ${{ env.ENV }}
  JWT_SECRET_KEY: ${{ env.JWT_SECRET_KEY }}
  JWT_EXPIRATION_MINUTES: ${{ env.JWT_EXPIRATION_MINUTES }}
  DATABASE_DEV_URL: ${{ env.DATABASE_DEV_URL }}
  DATABASE_TEST_URL: ${{ env.DATABASE_TEST_URL }}
  REDIS_URL: ${{ env.REDIS_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
